services:
  - type: web
    name: nature-market-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000

  - type: web
    name: nature-market-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: npx serve -s frontend/build
    staticPublishPath: frontend/build
